## Revising the basics after long

In [1]:
x = 0
while x < 12:
    x += 1
    if x == 3:
        continue
    print(x, end=' ')
print()
print('3 is not included')

1 2 4 5 6 7 8 9 10 11 12 
3 is not included


In [2]:
num = [i for i in range(1,12)]
num

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [3]:
# while with else
counter = 0
while counter < 10:
    print('Power Plant status : SAFE')
    counter += 1
else:
    print('CRITICAL !! CRITICAL!!')


Power Plant status : SAFE
Power Plant status : SAFE
Power Plant status : SAFE
Power Plant status : SAFE
Power Plant status : SAFE
Power Plant status : SAFE
Power Plant status : SAFE
Power Plant status : SAFE
Power Plant status : SAFE
Power Plant status : SAFE
CRITICAL !! CRITICAL!!


In [4]:
# link list
from collections import deque

myQ = deque()
myQ.append('I')
myQ.append('love')
myQ.append('idk')
myQ

deque(['I', 'love', 'idk'])

In [5]:
myQ.pop()

'idk'

In [6]:
myQ

deque(['I', 'love'])

## performing various search algorithm

In [7]:
# linear search
mylist = [1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 47]
mylist.index(37)

12

In [8]:
mylist = [1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 47] #defining the list of prime numbers
searchItem = int(input('Enter the number to be queried : '))
found = False
for i in range(len(mylist)):
    if mylist[i] == searchItem:
        found=True
        print(f'Search located at index {i}')
        break
else:
    print('No result found')


No result found


In [9]:
# binary search
def binary_search(arr, query):
    # repeat until low and high pointers meet each other
    low=0
    high=len(arr)-1
    while low <= high:
        mid = low + (high-low)//2

        if arr[mid] == query:
            return mid
        elif arr[mid] < query:
            low = mid + 1
        else:
            high = mid-1
    return 'No match'

In [10]:
mylist = [1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 47]

In [11]:
binary_search(arr=mylist, query=13)

6

In [12]:
binary_search(arr=mylist, query=12)

'No match'

In [15]:
word=["apple","mango","banana","fig","strawberry"]
word.sort(reverse=True)

In [16]:
word

['strawberry', 'mango', 'fig', 'banana', 'apple']

In [17]:
# combining the dictionary

# combine keys respective values from to dictionary variable
A={'a':72,'b':17,'c':8}
B={'a':1308,'b':1,'c':12}

In [18]:
A

{'a': 72, 'b': 17, 'c': 8}

In [19]:
B

{'a': 1308, 'b': 1, 'c': 12}

In [21]:
combineDict = {}

for key in A.keys():
    if key in B.keys():
        combineDict[key] = []
        combineDict[key].append(A[key])
        combineDict[key].append(B[key])


In [22]:
combineDict

{'a': [72, 1308], 'b': [17, 1], 'c': [8, 12]}

In [29]:
# variable arguments

def printinfo(arg1, *vararg1):
    print(f'Numbers are \n{arg1}')

    for entry in vararg1:
        print(entry)

    return

In [30]:
printinfo(12)

Numbers are 
12


In [31]:
printinfo(12,34,63,145)

Numbers are 
12
34
63
145


In [34]:
square = lambda x:x**2

In [35]:
square(3)

9

In [38]:
my_list = [1,5,4,6,11,34,12]
new_list = list(filter(lambda x:(x%2 == 0), my_list))

In [39]:
new_list

[4, 6, 34, 12]

In [41]:
# reading the files

q = open('nfak.txt','r')
q.readlines()

['Wo maane na maane, marzi hain unki \n',
 'Magar unko purnam, manaa kar to dekho \n',
 'Hamesha hue dekh kar mujhko barham \n',
 'Kabhi ek baar muskura ke bhi to dekho \n',
 '\n']

In [42]:
q.close()

In [59]:
import numpy as np

In [60]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
np.array([[2,5],[7,4]], dtype=complex)

array([[2.+0.j, 5.+0.j],
       [7.+0.j, 4.+0.j]])

In [62]:
a = np.array([1,4,7], dtype=complex)
a

array([1.+0.j, 4.+0.j, 7.+0.j])

In [63]:
a.imag = np.array([2,5,4])

In [64]:
a

array([1.+2.j, 4.+5.j, 7.+4.j])

In [72]:
p = np.arange(10)**2

In [68]:
x = [1,2,3,4]
a = np.asarray(a=x)
a

array([1, 2, 3, 4])

In [69]:
type(a)

numpy.ndarray

In [70]:
type(x)

list

In [75]:
s = slice(2,17)

In [76]:
p[s]

array([ 4,  9, 16, 25, 36, 49, 64, 81])