# Starting up with Finance modeling

In [1]:
vu = 1.5
vd = 3.75

vu , vd represents the up and down prices as random variables

In [2]:
type(vu)

float

In [3]:
vu + vd

5.25

Now it is always super useful if we can leverage the help of arrays for our calculation

In [4]:
import numpy as np 

v = np.array([1.5, 3.75])
v

array([1.5 , 3.75])

In [5]:
v.shape

(2,)

In [6]:
v + v 

# look easier it gets with the arrays 

array([3. , 7.5])

In [8]:
S = np.array((20,5))  # defining the uncertain prices of the stock
K = 15  # strike price 
C = np.maximum(S - K , 0) # payoff , calculated as element wise maximum calculations

In [9]:
C

array([5, 0])